### ISSUE TITLE
My measurements

### ISSUE THREAD

**Issue by buybackoff** [xoofx/Fast1BRC#1]
Salut Alexandre,

To avoid issues like I had with @nietras here is a preview of my measurements before I publish.

For the extended dataset that I prefer, you have almost made it to the top.

![image](https://github.com/xoofx/Fast1BRC/assets/489852/7c4f092e-554e-46d1-a849-56155060ee51)

But with the default dataset I would expect at least 2x gain, bit not. I have two such datasets.

![image](https://github.com/xoofx/Fast1BRC/assets/489852/8bfaecbf-a26c-4bec-bdde-9e8457e41c61)

![image](https://github.com/xoofx/Fast1BRC/assets/489852/a1ac003e-8943-44ac-b36f-eca2932069c2)

The methodology is described [here](https://hotforknowledge.com/2024/01/13/7-1brc-in-dotnet-even-faster-than-java-cpp/#methodology).

**Comment by xoofx** [comment]
Thanks! I didn't look at other datasets but just used the default 1B one, so some defaults or optimizations might not work well with other cases. For example:

> The extended dataset with 10K random weather station names

Definitely a case where I could see that the defaults might not be optimized for this case. But that's weird that it is the opposite. 😀 Will check

**Comment by xoofx** [comment]
> To avoid issues like I had with @nietras here is a preview of my measurements before I publish.

Oh, what do you mean by issues? 😅

**Comment by xoofx** [comment]
And nice, didn't know that you wrote an entire article, congrats! ☺️

**Comment by buybackoff** [comment]
> Thanks! I didn't look at other datasets but just used the default 1B

I will say again: your 10K results are great! But on my Linux machine your results on the default dataset are much slower than expected. Maybe you have some hardcoded assumptions about CPU count or something like that?

**Comment by buybackoff** [comment]
> Oh, what do you mean by issues? 😅

Nothing worth mentioning ATM, we have sorted it out 😄 Haven't we, @nietras?

**Comment by buybackoff** [comment]
> And nice, didn't know that you wrote an entire article, congrats! ☺️

Thanks!

**Comment by xoofx** [comment]
> But on my Linux machine 

Yeah, I would not be surprised of a different behavior. I only benchmarked on Windows x64 (and tried M1 ARM64 as well, seems it worked ok there)

**Comment by xoofx** [comment]
Double checked with 10k and regular dataset and the numbers on my machine feel normal:

![image](https://github.com/xoofx/Fast1BRC/assets/715038/64fb7bbf-269a-49d3-9cb6-c262591482fc)

Also, I checked on Linux (WSL2) and it seems even doing slightly better than on Windows.

Trying with your repository with latest version on the same dataset:

![image](https://github.com/xoofx/Fast1BRC/assets/715038/a5f9e1d1-4942-4d15-a771-969516cae309)

Something seems off on your machine. I would believe that it is more IO related, but can't be certain. For example, on my machine, I'm running almost 2 times faster on all datasets but you seem to indicate that it's not the case on your machine. You should probably try to run your benchmarks on different machine specs.

**Comment by buybackoff** [comment]
When you say your Ryzen is at 60W what does that mean? I [see](https://www.cpubenchmark.net/cpu.php?id=5031&cpu=AMD+Ryzen+9+7950X) that its typical TPD is 170W. Is your CPU frequency fixed? For a cross-check it would be nice to calculate the sum of frequencies for all cores and scale the results across machines. (BTW is there a term for it? E.g. for my machine it's 2.5x6 = 15 GHz hyperthreaded)

I restarted the machine and now see meaningful numbers. Do not know what happened yesterday, I'm running the same commands.

**Comment by xoofx** [comment]
> When you say your Ryzen is at 60W what does that mean? I [see](https://www.cpubenchmark.net/cpu.php?id=5031&cpu=AMD+Ryzen+9+7950X) that its typical TPD is 170W. Is your CPU frequency fixed?

Yeah, I limit the power consumption of my machine as suggested by @nietras a while back, I discovered that it's only 10% slower at 60W (benchmarks [here](https://browser.geekbench.com/user/438490)). CPU frequency is not fixed (because it adapts to thermal power requirement), but when you run things with hyperfine, it should not a big deal.

**Comment by buybackoff** [comment]
But what is the average frequency during the runs? No need for an exact number, just your guess, please.

**Comment by xoofx** [comment]
> But what is the average frequency during the runs? No need for an exact number, just your guess, please.

It's clocking at `4.05 GHz` when running 10 times the 10k (Base speed is `4.50 GHz`)

**Comment by buybackoff** [comment]
Oh, it looks like WSL uses only half of the cores. The scaling makes sense then for both Windows and WSL

![image](https://github.com/xoofx/Fast1BRC/assets/489852/08667ff9-11a2-4462-a57d-346ea3079f23)

![image](https://github.com/xoofx/Fast1BRC/assets/489852/f3d49659-8e62-4ef3-9aa0-a70dc5cf132a)

**Comment by xoofx** [comment]
> Oh, it looks like WSL uses only half of the cores. The scaling makes sense then for both Windows and WSL

You mean WSL, not WSL2? Not sure I noticed that on WSL2, same machine specs...

Btw, looking at the accuracy of the results, It seems that your version is off on 2 lines with my 10k run:

![image](https://github.com/xoofx/Fast1BRC/assets/715038/fd296409-9107-4388-b019-0c022ab9037a)

I compared it with other versions and it seems consistent (well, the one that are working with 10k 😅 ), so there might an issue somewhere in your code.

**Comment by buybackoff** [comment]
Will figure it out today. 

At the moment, the results are:

![image](https://github.com/xoofx/Fast1BRC/assets/489852/14b307ab-3235-4d6f-b603-dd102aab6519)

Does it make sense to you?

**Comment by xoofx** [comment]
> Does it make sense to you?

Dunno, on my machines (Ryzen Windows 11 but also on M1 Pro), I have opposite numbers 😀, my version is twice as fast as yours. Nietras version is also slightly faster than mine, but not by that margin, so something is weird there.

**Comment by buybackoff** [comment]
It's Linux vs Windows probably

**Comment by buybackoff** [comment]
Could it be too sensitive to CPU caches? My RAM on the bench machine is not the fastest, DDR4 3200.

Will check relative numbers on Windows as well.

**Comment by nietras** [comment]
My RAM is DDR4 3600 and I see same numbers like @xoofx, with our implementations being roughly twice as fast as yours. I would think file IO in WSL is severely hampered from that. Can't use WSL for perf testing that has anything to do with IO. Hence either use windows or proper linux.

**Comment by xoofx** [comment]
Oh, @buybackoff you were running all your tests on WSL? (I thought when you said Linux, that was a real Linux or at least WSL2, not WSL). That would explain, WSL has terrible performance in terms of IO and a large part of this benchmark is related to IO.

**Comment by nietras** [comment]
Comparing WSL to proper Linux is not a good idea anyway. This assumes that WSL is what has been used for your benchmarks, I may have misunderstood of course.

**Comment by buybackoff** [comment]
I assume you have never read even up to the Methodology section
https://hotforknowledge.com/2024/01/13/7-1brc-in-dotnet-even-faster-than-java-cpp/#methodology


This task is not IO bound, the file is in the page cache. But I also have NVMe 4.0 Firecuda 530 on that host.

**Comment by nietras** [comment]
> performance is measured on a quiet 6C/12T Alder Lake CPU fixed at 2.5 GHz (disabled turbo), 32GB DDR4 3200, and Debian 12 in a privileged LXC container in Proxmox. With fixed base frequency the thermals are perfect (< 35°C) and no throttling happens even under sustained 100% load.

> The timings are measured with the hyperfine --warmup 1 --runs 5 './1brc path/to/file'.

But why then are you mentioning WSL above? It's very confusing not to have a clear indication of what is what and where. 😅

I have no idea how that container has been set up but something must be wrong with it, I'd think. Numbers are way off.

**Comment by xoofx** [comment]
> I assume you have never read even up to the Methodology section

Wait a minute, `privileged LXC container in Proxmox` is probably the culprit. Benchmarks should always be run on real HW without any kind of virtualization, otherwise it's impossible to reason about them.

We are both measuring very different numbers on both Windows 11 + Ryzen and Apple M1.

**Comment by buybackoff** [comment]
First, are you using my latest master?

> Wait a minute, privileged LXC container in Proxmox is probably the culprit. Benchmarks should always be run on real HW without any kind of virtualization, otherwise it's impossible to reason about them.

A container is not a VM, it has direct access to CPU/memory and overheads are minimal if exist at all. Anyway this is the real-world scenario in a cloud. No way I'm polluting my Proxmox host with all this stuff. And by the way, if you have WSL 2 installed on Windows then Windows itself runs as a privileged VM in Hyper-V.

> But why then are you mentioning WSL above?

Because @xoofx showed his results in his WSL.

**Comment by xoofx** [comment]
> A container is not a VM, it has direct access to CPU/memory and overheads are minimal if exists at all. Anyway this is the real-world scenario in a cloud. No way I'm polluting my Proxmox host with all this stuff. And by the way, if you have WSL 2 installed on Windows then Windows itself runs as a privileged VM in Hyper-V.

I know that WSL2 is running with Hyper-V, but please run your benchmark on real hardware. I don't agree with your methodology at all and I'm pretty sure that's the problem from your side. I will publish my own results on real HW on my repo as well, because what you present is completely off.

> Because @xoofx showed his results in his WSL.

What do you mean? All my results above were on Windows. I'm confused.

**Comment by buybackoff** [comment]
> What do you mean? All my results above were on Windows. I'm confused.

You said

> Also, I checked on Linux (WSL2) and it seems even doing slightly better than on Windows.

but then I missed the part that were my numbers. It looked as if it was just running on half the cores.

> No memory mapped file but RandomAccess reopening the same handle per thread

So if your numbers are Windows-only at the moments, how RandomAccess  would compare with mmap on Linux? I believe I've seen somewhere @nietras mentioned that mapped files are much faster on Linux.

**Comment by nietras** [comment]
> believe I've seen somewhere @nietras mentioned that mapped files are much faster on Linux.

I didn't conclude, but merely asked if that could be the case? I also suggested running my impls mmap vs RandomAccess benchmarks to try to figure out what is going on here, which I am sure we all want. ☺️ At the very least this would mean I learn something 😅

Another theory could be some issue with multiple file handles and RandomAccess to same file in Linux vs Windows. Or differences in file io overhead and caching when doing such.

I don't know how easy it would be to boot Linux from a USB on our side... but I guess that's an option to investigate...

**Comment by xoofx** [comment]
> So if your numbers are Windows-only at the moments, how RandomAccess would compare with mmap on Linux? I believe I've seen somewhere @nietras mentioned that mapped files are much faster on Linux.

It could be, I have only quickly tested with WSL2 on the side and it was running at a similar speed than on Windows. 

Redouble checking on M1 and RandomAccess might not run as well there, so memory mapped files might be faster on these OS.

I developed and mainly benchmarked on Windows, so it might not be as efficient on other platforms. But on Windows, at least, we have consistent numbers showing 2x improvement compared to your version. I will check by having a path using memory mapped file just to confirm this.

**Comment by nietras** [comment]
@xoofx perhaps you could just try my version on mac?

**Comment by buybackoff** [comment]
I will do Windows shortly, just need to run to a market 🐟

**Comment by nietras** [comment]
As mentioned also BDN bench that compares the two, this is in process though...

**Comment by xoofx** [comment]
> @xoofx perhaps you could just try my version on mac?

Does it default to RandomAccess or memory mapped?

**Comment by nietras** [comment]
RandomAccess, but one line change. I can make a branch if you like? BDN bench has both.

Let me check if I messed up main, though... 😅

**Comment by nietras** [comment]
@xoofx main RandomAccess as fast as ever.

![image](https://github.com/xoofx/Fast1BRC/assets/10798831/b3ca633f-9832-43f8-b1c1-242d5994832b)

Change to memory mapped:

![image](https://github.com/xoofx/Fast1BRC/assets/10798831/21de7b94-feaf-4bbd-8e04-831d5d48b8cd)

And much slower:

![image](https://github.com/xoofx/Fast1BRC/assets/10798831/be88352e-cba7-49f1-90ad-a9e594be35ed)

**Comment by xoofx** [comment]
I have modified the latest of Fast1BRC to automatically use mmap or RandomAccess depending on the platform. So:

* On Windows, it is faster with RandomAccess and no mmap
* On Mac M1 Pro, it is faster to use mmap.
* On Linux WSL2 on the same Windows machine, it is running similarly to RandomAccess (so mmap or not doesn't matter)

Overall, it seems better to use mmap on non Windows machine (that's now the default of Fast1BRC).

I will try to publish more details results on all these platforms. I have also some Linux real HW box that I can run the test on directly.

**Comment by nietras** [comment]
I can of course do the same in my implementation, but I'd really like to know why? Is Windows mmap just really slow?

**Comment by nietras** [comment]
Updated my implementation to do the same switch. 

Anyways, if I were to conclude then the only reason our implementations were then 2x faster than others (incl. Java) was that memory mapped file is very slow on windows compared to sequential file reading. While on linux/macOS likely faster to use mmap.

**Comment by buybackoff** [comment]
@nietras Could you, please, fix that for Linux as well?

![image](https://github.com/xoofx/Fast1BRC/assets/489852/6b94023b-4399-40cf-9a08-f2e5b10c4dc9)


I will re-run both your version right now.

**Comment by xoofx** [comment]
Ran the benchmarks on my Windows machine and M1 Pro:

![image](https://github.com/xoofx/Fast1BRC/assets/715038/1333fb13-15c3-4699-a159-7970d9dae97f)

(Couldn't get your version @nietras on Mac, seems to crash at runtime - e.g M1 Pro doesn't have Vector256 for example, dunno if it is that problem)

> Could you, please, fix that for Linux as well?

Oh, I might have to change my version as well. Will check on a real Linux box to double verify, as it work on WSL2.

**Comment by nietras** [comment]
> ouldn't get your version @nietras on Mac, seems to crash at runtime 

@xoofx I run CI tests on macos and latest main should work on macos. As seen here https://github.com/nietras/1brc.cs/actions/runs/7518687755 (there was a crash due to Avx2 usage before). I really didn't optimize or check for ARM 😅
Could you expand on the error? What's the exception? Just run without hyperfine.

>  Could you, please, fix that for Linux as well?

@buybackoff same CI works on linux so could you expand on the mmap change? Why is it needed?

Will change of course.

**Comment by nietras** [comment]
@buybackoff the change you suggest fails testing with:
```
        System.IO.IOException: The process cannot access the file 'C:\git\oss\1brc.cs\test\measurements-1.txt' because it is being used by another process.
```
as it doesn't allow opening more than one. Trying to see of MemoryMappedFileAccess.Read fixes, but still wonder why this change needed. 😅

**Comment by buybackoff** [comment]
Sorry, it's no needed. It was failing yesterday.

**Comment by nietras** [comment]
I am happy I now have CI so I can 👉 😉

**Comment by nietras** [comment]
I am still working on the 10k real station names thing, though 😅 Had a bunch of new (old) ideas not sure when I will finish though.

**Comment by nietras** [comment]
Tagged `v0.2.0` in main with the mmap vs file/randomaccess switch.

**Comment by nietras** [comment]
@xoofx and @buybackoff I have a quick big improvement for 10k coming very soon! Below is new, used to be about 2.8s so now 1.7s.

![image](https://github.com/xoofx/Fast1BRC/assets/10798831/4b598feb-cd4f-4c2f-bb0d-1929f5288d5a)

**Comment by nietras** [comment]
Merged the new version into main. Let me know if anything fails and what is the issue on macOS that I need to fix.

**Comment by tivrfoa** [comment]
> > Oh, it looks like WSL uses only half of the cores. The scaling makes sense then for both Windows and WSL
> 
> You mean WSL, not WSL2? Not sure I noticed that on WSL2, same machine specs...
> 
> Btw, looking at the accuracy of the results, It seems that your version is off on 2 lines with my 10k run:
> 
> ![image](https://private-user-images.githubusercontent.com/715038/296535449-fd296409-9107-4388-b019-0c022ab9037a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzAxNTIsIm5iZiI6MTcwNTIyOTg1MiwicGF0aCI6Ii83MTUwMzgvMjk2NTM1NDQ5LWZkMjk2NDA5LTkxMDctNDM4OC1iMDE5LTBjMDIyYWI5MDM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDU3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjEzODhjNjU0ODExODA2NTJmMWEwY2QyZWRhYTljYmYxYTVlNzA2MmNlODVmMDc1OGQ2NDIyYjJhZWQ1ZjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5-tWgVdbVP_SDmopX5H6W_hzfrFty7wLZc_haEYouS4)
> 
> I compared it with other versions and it seems consistent (well, the one that are working with 10k 😅 ), so there might an issue somewhere in your code.

His solution does not work.
https://twitter.com/tivrfoa/status/1746297716974489965

Just mentioning here because it's a bit pointless (and unfair) to benchmark a wrong solution.

It can be also bad for other people, that might try to copy some of that code, and end up with broken code too.

**Comment by buybackoff** [comment]
@tivrfoa you may stop being so vocal about that 

https://github.com/buybackoff/1brc/commit/410799b0a06a31de4b2f6af2ab6fa0910e0e714c?diff=unified&w=0#diff-50d5d1069929df17bbf6f330e04035cfaafa17de2e48ab86ce2dbd0de338528aL75-L77

For 10K
![image](https://github.com/xoofx/Fast1BRC/assets/489852/6c644a1a-d425-4256-868b-e7357f821ac2)

**Comment by buybackoff** [comment]
@xoofx on Windows I have the same ratio `your/my time` as on your picture. On Linux, however, I see some improvements but they are not dealbreakers.
![image](https://github.com/xoofx/Fast1BRC/assets/489852/7601df0d-eb37-4cbf-ba42-cab280164c29)

10K time improved by 1 second.

**Comment by buybackoff** [comment]
If you don't believe me, there is a paper from researchers from Inria & et al.: https://inria.hal.science/hal-03337920/document

![image](https://github.com/xoofx/Fast1BRC/assets/489852/5ca3a948-8c8c-407b-a879-ef16ecb1b26d)

**Comment by xoofx** [comment]
> If you don't believe me, there is a paper from researchers from Inria & et al.: https://inria.hal.science/hal-03337920/document

In general, I will never run benchmarks in containers. I have seen legion of problems in my career with that, so that's my rule. 🙂 

The problem of difference is probably not related to the container though, but to the machine. I'm setup-ing a fresh ubuntu-22.04 with so that I will be able to run things on a real HW, slightly different from my Ryzen 7950X but it is a 7840HS, so close enough in terms of CPU.

**Comment by xoofx** [comment]
> Merged the new version into main. Let me know if anything fails and what is the issue on macOS that I need to fix.

So @nietras on a clean Ubuntu 22.04/x64 it's failing at https://github.com/nietras/1brc.cs/blob/3230222926367c9d64e4990e61b762750cad6b2f/src/Brc/Program.cs#L12

`Permission denied`, If I comment it, it runs fine.

**Comment by nietras** [comment]
So you don't trust my code I see 🤣 Not wanting to run it with sudo. 😜

Bad habit of mine perhaps but when benchmarking set your priorities! I guess I can do a try/catch of course.

**Comment by xoofx** [comment]
Here are the final results on my machines: 

![image](https://github.com/xoofx/Fast1BRC/assets/715038/31d71040-e982-4ec4-b6fc-d093b9fa69d0)

Some comments:

- Results are varying a lot! 📊
- Nietras solution is clearly more consistent and overall winning! 🥇
- The results vary vastly between HW / OS 💾
  - I believe one of the main differences of performance is the M.2/SSD disk access

That was an interesting challenge, considering the variations.

Closing the thread now, thanks all for the competition, that was fun! 🤗

**Comment by nietras** [comment]
Awesome, thanks, I'm surprised how good the mac M2 results are for mine, I did zero tuning for it and it's hybrid so should definitely have it's issues. Can I share the image on mastodon etc? Perhaps you will?

**Comment by xoofx** [comment]
> Can I share the image on mastodon etc? Perhaps you will?

Sure, I just posted it on [masto](https://mastodon.social/@xoofx/111755470365432385), feel free to reshare in other places. 😉

**Comment by buybackoff** [comment]
Interestingly I had a branch with RandomAccess, and if I just reuse that code it's significantly faster on Windows. I was testing on Linux from the beginning...

I have just read your code and the hash trick. Would you use it in a bank if the file was `account_holder_name;account_delta`?

Frankly I did not even pay attention and would not think to cut corners like that. But it turns out many implementations did that.

I even tried already to find a collision with several billion random strings so far. And I understand it's unlikely, but not cryptographically-unlikely. Unfortunately the brute-force is RAM bound and I only have 128 GB, that's enough for less than 5 minutes of crunching.

**Comment by xoofx** [comment]
> I have just read your code and the hash trick. Would you use it in a bank if the file was account_holder_name;account_delta?

Nope, but these are weather stations right, so that's ok. 🙂 

Also, in this kind of cases, you could always verify things everytime there is a new station name coming from another source (you get a notification) and verify that your hash won't ever collide. By the time does collide, you will be able to change your plan, use a stronger different/safer hash...etc, it will be probably in a million of years, if you have enough cities. Until then, profit.

**Comment by nietras** [comment]
FYI the official challenge already discussed this in https://github.com/gunnarmorling/1brc/pull/186 (same hash btw), given rules it was dismissed

**Comment by buybackoff** [comment]
@xoofx Could you, please, re-run your benchmarks with my latest commits? 

It should be significantly faster than @nietras on Linux. On Windows, it should be much closer since I also switched to RandomAccess there.

**Comment by xoofx** [comment]
> @xoofx Could you, please, re-run your benchmarks with my latest commits?
> 
> It should be significantly faster than @nietras on Linux. On Windows, it should be much closer since I also switched to RandomAccess there.

It's not significantly faster but within the same zone of all 3 implementations now, so congrats. At some point it's not surprising. There is little left to optimize here. 🙂 (There is the case of MacOS that is a bit more a mystery for me, but I won't spend time investigate more 😅)

**Comment by buybackoff** [comment]
Thank you, @xoofx ! 

It's a mystery why your code refuses to run on my machine at full speed. Every other result scales correctly, including what lehuyduc and Java published. Do you have hyper-threading enabled on your machines?

Also quite confusing is the fact that if CPU-bound main loop over a byte span is more efficient on Linux, and on Windows I use basically the same RandomAccess loop as the other two, then relative result on Windows drops significantly. Maybe my async idea does not pay off and the loop is not exactly the same. If it's not too difficult, could you, please, change [this line](https://github.com/buybackoff/1brc/blob/760743e579e8286bdca794bc7c5a7e5cdf18d460/1brc/App.cs#L51) to use `ProcessMode.RandomAccess` and run it only on the last 7840 machine on Windows?

**Comment by xoofx** [comment]
> Maybe my async idea does not pay off and the loop is not exactly the same. If it's not too difficult, could you, please, change [this line](https://github.com/buybackoff/1brc/blob/760743e579e8286bdca794bc7c5a7e5cdf18d460/1brc/App.cs#L51) to use `ProcessMode.RandomAccess` and run it only on the last 7840 machine on Windows?

It is closer/equal to Nietras's version (all versions fluctuate with 5-7% between runs). I also tried async when I started (with double buffering), but I was not able to achieve better perf than sync.
